steps:
  - name: hashicorp/terraform:1.6
    entrypoint: sh
    args:
      - -c
      - |
          terraform init
          terraform plan -var-file=terraform.tfvars
          terraform apply -auto-approve -var-file=terraform.tfvars

options:
  logging: CLOUD_LOGGING_ONLY
